POST http://localhost:3001/api/jobs
Content-Type: application/json

{    
    "name_company":"Facebook",
    "url_comp": "facebook.com",
    "cuidad": "Chicago",
    "modo": "Remoto",
    "tipo": "Part time",
    "titulo_vacante": "DevOps",
    "descripcion": "blablablablabla",
    "userId": "619ad1773a332e798e6010bd"
}

