POST http://localhost:3001/api/jobs
Content-Type: application/json

{
    "name_company":"Prueba 10",
    "url_comp": "Prueba.com",
    "cuidad": "San francisco",
    "modo": "Remoto",
    "tipo": "full time",
    "titulo_vacante": "Data",
    "descripcion": "Lorem insup"
}

