POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username":"vanessa",
    "name": "vanessa",
    "password": "unacontraseniamuysegura",
    "job": "19a7738ecf01d0c1decb2f5"
}
